name: bitirme_parent_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  preload_page_view: ^0.2.0
  url_launcher: ^6.2.4
  http: ^1.2.0
  carousel_slider: ^4.2.1
  flex_color_scheme: ^7.3.1
  flutter_localization: ^0.2.0
  permission_handler: ^11.3.1
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.3
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.1.0
  flutter_glow: ^0.3.0
  popover: ^0.2.8+2
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^5.2.1
  provider: ^6.1.1
  flutter_swiper_view: ^1.1.8
  image_cropper: ^7.0.3
  get: ^4.6.6


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/logo/


